name: PR
on: [pull_request]
jobs:
  pr:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/iomorphic/image/dev-py:latest
      volumes:
        - /usr/bin/docker:/usr/bin/docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - run: just pr
